anchor_version = "0.24.2"
solana_version = "1.10.30"

[scripts]
test = "yarn mocha tests/**/*.spec.ts"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
solana_nft_programs_payment_manager = 'pmvYY6Wgvpe3DEj3UX1FcRpMx43sMLYLJrFTVGcqpdn'

[programs.devnet]
solana_nft_programs_payment_manager = 'pmvYY6Wgvpe3DEj3UX1FcRpMx43sMLYLJrFTVGcqpdn'

[programs.testnet]
solana_nft_programs_payment_manager = 'pmvYY6Wgvpe3DEj3UX1FcRpMx43sMLYLJrFTVGcqpdn'

[programs.localnet]
solana_nft_programs_payment_manager = 'pmvYY6Wgvpe3DEj3UX1FcRpMx43sMLYLJrFTVGcqpdn'
